version: 2

jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      GRADLE_OPTS: -Xms3200m -Xmx3200m
      JVM_OPTS: -Xms3200m -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    - run:
        name: Building project
        command: |
          gradle build remapJar remapSourcesJar --stacktrace

    - run:
        name: Running tests
        command: |
          gradle --stop
          gradle check

    - store_test_results:
        path: build/test-results

    - store_artifacts:
        path: build/libs
        destination: jars