version: 2

jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    - run:
        name: Fetching dependencies
        command: gradle dependencies

    - run:
        name: Building and remapping jars
        command: |
          gradle --stop
          gradle cleanLoomMappings build remapJar remapSourcesJar --stacktrace

    - run:
        name: Running tests
        command: |
          gradle --stop
          gradle check

    - store_test_results:
        path: build/test-results

    - store_artifacts:
        path: build/libs
        destination: jars